### ISSUE TITLE
kernel 4.14

### ISSUE THREAD

**Issue by Aodren92** [PacktPublishing/Linux-Device-Drivers-Development#2]
hi,
its not an issue, but i had to modify 
https://github.com/PacktPublishing/Linux-Device-Drivers-Development/blob/master/Chapter03/std-timer.c

if i wanted to compile :
they change the API for the timer
the callback function, line 8  is now :
`void    my_timer_callback(struct timer_list * list) ;`

and the init is now :
```
static int __init my_init( void )
{
    int retval;
    pr_info("Timer module loaded\n");

    timer_setup(&my_timer, my_timer_callback, 0);
    pr_info( "Setup timer to fire in 300ms (%ld)\n", jiffies );

    retval = mod_timer( &my_timer, jiffies + msecs_to_jiffies(300) );
    if (retval)
        pr_info("Timer firing failed\n");
 
    return 0;
}
```
I don't know if you want to keep your code updated with the new kernel version or not :)

**Comment by Kiogora** [comment]
For reference for anybody else, see the LWN article here: https://old.lwn.net/Articles/735887/

**Comment by ManikandanKurup-Packt** [comment]
Thank you for the fix!
